"""Generate custom_components/ha_flightseats/airports.py.

Needs the dev-only package `airportsdata` (pip install airportsdata); the integration itself
does not depend on it. Edit CODES and run from the repo root:

    python docs/dev/make_airports.py
"""
import airportsdata

REGIONS = {
    "Australia": "SYD MEL BNE PER ADL CBR OOL HBA LST DRW ASP CNS TSV MKY PPP HTI ROK GLT BDB HVB MCY "
    "BNK CFS PQQ NTL TMW ARM DBO WGA ABX MQL AVV BME KTA PHE KGI GET EPR ALH LEA AYQ KNX ISA EMD LRE "
    "MOV DPO BWT NLK LDH XCH CCK WTB",
    "New Zealand": "AKL WLG CHC ZQN DUD NSN NPE ROT TRG HLZ NPL IVC PMR WHK GIS",
    "Pacific": "NAN SUV APW TBU RAR PPT NOU VLI HIR POM LAE GUM HNL OGG KOA LIH",
    "Asia": "SIN KUL BKK HKG NRT HND KIX NGO FUK CTS OKA ICN GMP PEK PVG CAN SZX CTU TPE DPS CGK SUB MNL "
    "CEB SGN HAN DAD SAI KTI VTE RGN DEL BOM BLR MAA HYD CCU CMB MLE KTM DAC ISB LHE KHI PEN LGK HKT "
    "CNX USM BKI KCH BWN MFM",
    "Middle East": "DXB AUH DOH DWC BAH KWI MCT RUH JED AMM TLV BEY CAI IST SAW",
    "Europe": "LHR LGW MAN EDI GLA DUB CDG ORY AMS FRA MUC BER HAM DUS ZRH GVA VIE BRU CPH ARN OSL HEL MAD "
    "BCN LIS OPO FCO MXP VCE NAP ATH PRG WAW BUD KEF",
    "North America": "LAX SFO SAN SEA PDX LAS PHX DEN DFW IAH AUS ORD MSP DTW ATL MIA MCO TPA JFK EWR LGA "
    "BOS IAD DCA PHL CLT BWI SLC ANC YVR YYZ YUL YYC YEG YOW MEX CUN PVR SJD",
    "South America": "GRU GIG EZE SCL LIM BOG UIO PTY",
    "Africa and Indian Ocean": "JNB CPT DUR NBO ADD CMN LOS ACC MRU SEZ",
}
OUT = "custom_components/ha_flightseats/airports.py"

data = airportsdata.load("IATA")
codes = [code for group in REGIONS.values() for code in group.split()]
dupes = {c for c in codes if codes.count(c) > 1}
missing = [c for c in codes if c not in data]
assert not dupes, f"duplicate codes: {sorted(dupes)}"
assert not missing, f"codes not in airportsdata: {missing}"

cities: dict[str, int] = {}
for code in codes:
    cities[data[code]["city"]] = cities.get(data[code]["city"], 0) + 1


def short_name(name: str) -> str:
    for word in (" International Airport", " Airport", " International", " Intl"):
        name = name.replace(word, "")
    return name.strip()


labels = {}
for code in codes:
    entry = data[code]
    place = entry["city"]
    if cities[place] > 1:  # several airports for one city: show the airport name instead
        place = short_name(entry["name"])
    labels[code] = f"{code} – {place}, {entry['country']}"

with open(OUT, "w", encoding="utf-8") as handle:
    handle.write('"""Airports offered in the watch form.\n\n')
    handle.write("Generated by docs/dev/make_airports.py. Any other IATA code can still be typed in.\n")
    handle.write('"""\n\nAIRPORTS: dict[str, str] = {\n')
    for code, label in sorted(labels.items()):
        handle.write(f'    "{code}": "{label}",\n')
    handle.write("}\n")
print(len(labels), "airports written to", OUT)
